---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAzGQTPQsy9Z0mgH0aVjBJdy6mIif6EvJ9K6mQnCP2esS4IPTOzZxUASpwnjwl9O2M8400ZCdMU6FlsE6oF+1da+zAn243g0YVnR2avI1BtzZe2bjXaO2bUya0B9u1+bKZDplp6ELZdxuVLvfSqyEDdjU4AmCuGM89byGG7lWHItQ2KGhYcv9PwpGMljza6IIO0Rmu40JJFwTzy98DlSy4wnx6nSLL/UCV2VLam30rC6i/EFk4ge34AKFix99ALKKr+zdEUv0RSzriZmSdaijMAk6DRruCpFWMceyPBWpOEYSAFAJELYc4MviXr1RWqFmoc4yHIuHI/2XjSvEfGYalheTd8sJWROV53rFM1Osf3aKW/E98MpUO4yTtL+Dht8rxO7yxChmHlkJJumIe59bfBBpKTGESsmORV8FOJN3jE4Fva/GY8K2HFroYHrEO0JAlTlqZC+FZVoWKapICmSgH4k9KNrjqGQ/SCR/7sVpLB3he1TA+67BnlVL+ezUnI+DNDT++I2LF8/STsrGuP29MlixPjJpxkSimnH0nijVXqaO2t/vLIYkfIkW0lnmu83F/DugCp/olTPh8RzWglzEcJos70OTT8iixSbVgo+zPuCHbfcbVnazFBRURR6UY45wunBrFDOjAJtx4Y+FyECLgR2MilzAjL8Yhr0LEJc0PIPVOUM3AScEbQGtR3/4V25GgDaCWN2kXfSt4H+o3/Aob8PwglwhheGfM=
    admin-user: AgASPTEw7nSkqazDDPpgWiPMbH/5Y4ElCYod+mFIgRe1mImq4PJ1SFfSyfgfMFY1FpwS4nQsoNqGg2th8ukd0LaAtDt3vbBHv6dc6X8+DFRsMuPpTHup9SJk6OT20YU1NguDjHntseMO6iBEU9p7b5TcA7gpkhynLS0/r7VWfUiDjPUsvngFs3gPJUmPxSY5R8k9LydrnFhZk62I2u2fjeeRNf4ypu0Fh50vmpgrHXqPhyqVplfohBp2wx0pQEmLQWa4r5oA3398y8caj7CtTwCXmrM6Sv9KFVRgTmpiposg+e3Lq7IphZqjpNG22jPVvGVitWM4x5bto5rUXa1le5pte1UDIsd39UP5IaNicwTLavjJV2eIV71JWSlv1LRsGxkheW4nv366Ad1V4FANItG1YhOZ3FVWm7Rd3IT+mU/alSl0VtDHS9iM6A3fULHpB/JfPWKS4RRpONg3ObdWpsjjZTYLPcWfsBNNj7HfgTjgZJtvTtjlTnRIBLAXdSeY/rp7XXUkpQM2YEWZ6VS75q5qpzpLcyY0AmXbS2rFvxmVUt2195YquOljR5II5S8y/wEgakt/MT6wNznzA+jMv5MZB1+q+k477yGiZi5kFJc7pE8yiWzRkmqCKO8VxM/X+oblw+HkfGBliP55QddBibwIY/9Q9nB08Bbc/4Yaug+nUm/g9FUTkeIX9iUQcb9fdVrAcVs4rQ==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
