---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBgrR4/xwUgShp0fLcWxz5BOJsWlSP9hkiojEphzNovAeBbN/shbi4CE+Q/517lMp6Zz4pspl9bSIMzUDcWSuZ2EfvVQs7PQu6NvkmIMWm6qfr5QEZZQtF6rI09/Do3ZlFUS190h4bLBAzNubXcKdW+HdhzypkyGtHc6C/RYOMiPIHoQOE/WUKW2VSC1YJxg3BEFXuPU9cvuStRhIqo2sYhXUKCuinItanL7sGfCMCpaKlYdlOhzTpkpzpN2zr6qAFvM8WrTiim3wSgBGYyrUqvOnZO9+lpPIc02tIjuEVU9hKx39livFUiL71nHn0PZ5n8MiAYmCxE2Tu42xkTt6xKFUN5OYBQ7lLxn8f2k0kpMSiv3vXeOeNiM9rQUASTNN1/ah3Vz88zQxo10Cv8t143BwVpD7bcW84ni0/FHbO0A6pj2twujc3+fiMtQEi3NMThbo5E11fBrEkflDBHM+HBluWojGDTw2QmA6pS6hdu7eqKmIfto+okSX/8OHgYAGAApdPcHy+ECi28hHCbUPvJV930jHDDPMn5eMlL2SHgEN8dTmaZPB7UZOMginr07UBkh66fGjjP2suIGf9fBrlV21JY7n5YGjOxZLxGJZ+Zs7WaoYPi4TBhk9FOoH4YecHXK8K0oybWK9yxnM3jcPrSaX2HxUFmNkcbKM6Ek6ATzJ5ULY/zEU99RDy8g2yyXxxTYhAnYnM+odFwStWbYR+QTeTUGs+3Y9c=
    admin-user: AgB5M05KCM4j99vphCw7eVUOM6PV2jUjsMC92onE4NyDaTaus4dDxMdL/arPPU+tpbIYcVq92oLDolWUovoK1bofZI90ufMBjeYNAFiC8/5CROD8IrFk1WaxctfmJgjFDba56unWaJ3GuFoC2IbvZuE+kexoXW3AoKJh6ZJ+/HbfDPGiruN2sJRdkjXc/hvFipFxD8Rmn1QbBNV8Eu+wx2RVuxhqrZAUIJYn8+fXc+w8mg6HxeltJenEKrrC9g4ZHp1wfNkyj4jRtkq+539amLXiW5Ti/Eh0M3QQtN8EuNiWl/Wyn/Hhv5o5eHG1TzTblgNY6e/3+3RNDk4kSkKW4bULO9XNYXDmzIhOxaDuJ3a0mp9QY0qEtSr472Adj81Lk3BQOooWEC4848e8CdYrM2piBkGCQ8Jtbt6b7Z7sZU5RsBMNvSctTSVxs080jIVWZZlobHFnVUglD5kaTOF6j1pC05oiZPT1MHKtUUVmFcFtcImQI0BGDCXS7qMCbaGv7K1hMiL5bpyZK8rCya5KAd58aZYHpiEFv465Pv9sWRA+eqDQoM7+73oqOl0qJ55jDmr5++6BsbKtOi6/tTVWMa2mug0wISI1qRqMFJylQJJ6H8niB9gGtirCuYPb8XNg1Q1+8WVy45DO3GysIysqPuDp700T5wT/5qxddUk8MRezqP3vTAfW6QYy4vVwf9ei1oO0qruaEg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
